interface TickResult { heartbeatSent:boolean; capabilitiesPublished:boolean; tasksProcessed:number; succeeded:number; failed:number; errors:number }
type RemoteStatus='unconfigured'|'connecting'|'online'|'degraded'|'offline';
interface MetricSnapshot { memoryPercent:number; cpuPercent?:number; netRxBytesPerSec?:number; netTxBytesPerSec?:number; gpuUtilPercent?:number; gpuTempC?:number; gpuName?:string; gpuVramMB?:number; recordedAt:number }
interface StatusResponse extends MetricSnapshot { mode:string; connector:string; agentStatus:string; apiHost:string; apiPort:number; lastHeartbeatAt:string|null; lastHeartbeatSuccessAt:string|null; lastHeartbeatErrorAt:string|null; consecutiveHeartbeatFailures:number; lastRemoteError:string|null; remoteStatus:RemoteStatus; configurationIssue:string|null; lastTick:TickResult|null; pluginCount:number; capabilityCount:number; startedAt:string; hostId:string|null; taskCount:number; platform:string }
interface PluginSummary { id:string; name:string; version:string; schemaVersion:number; runtime:string; description?:string; deployment?:{type:string;[key:string]:unknown}; capabilities:Array<{name:string;description?:string;inputSchema?:CapabilitySummary['inputSchema'];outputSchema?:unknown}>; enabled:boolean; status:'registered'|'disabled'|'unsupported'|'error'; reason?:string }
interface TaskArtifact { name:string; localPath:string; exists:boolean; sizeBytes:number|null }
interface TaskSummary { taskId:string; capability:string; pluginId:string; input:unknown; status:string; output:unknown; error:{message:string}|null; createdAt:string; updatedAt:string; artifacts:TaskArtifact[] }
interface CapabilitySummary { name:string; pluginId:string; description?:string; inputSchema?:{required?:string[];properties?:Record<string,{type:string}>} }
interface ConfigResponse { hostId:string; name:string; serverUrl:string|null; apiKey:string|null; agentIntervalMs:number; startOnLogin:boolean; logRetentionDays:number; apiKeyConfigured:boolean }
interface StorageInfo { logsPath:string; cachePath:string; pluginsPath:string; logsBytes:number; cacheBytes:number; pluginsBytes:number }
interface UpdatePlan { deploymentId:string; artifactUrl:string; artifactName:string; artifactSha256:string; artifactSizeBytes:number }
interface PersonalHubApi {
  getStatus():Promise<StatusResponse|null>; getMetrics():Promise<MetricSnapshot>; getMetricHistory(range:'minute'|'hour'):Promise<MetricSnapshot[]>; runAgentTick():Promise<TickResult>; startAgent():Promise<{ok?:boolean;error?:string}>; stopAgent():Promise<{ok?:boolean;error?:string}>;
  getPlugins():Promise<PluginSummary[]>; importPlugin():Promise<{id:string;name:string}|null>; copyText(value:string):Promise<{ok:boolean}>; setPluginEnabled(pluginId:string,enabled:boolean):Promise<{ok:boolean;restartRequired:boolean}>; deletePlugin(pluginId:string):Promise<{ok:boolean;restartRequired:boolean}>; getTasks():Promise<TaskSummary[]>; getCapabilities():Promise<CapabilitySummary[]>; createTask(capability:string,input:unknown,execute?:boolean):Promise<TaskSummary>; revealArtifact(taskId:string,localPath:string):Promise<{ok:boolean}>; deleteTask(taskId:string,deleteArtifacts?:boolean):Promise<{ok:boolean;deletedArtifacts:number}>; getLogs():Promise<string>; getConfig():Promise<ConfigResponse|null>; getStorageInfo():Promise<StorageInfo>; openStoragePath(kind:'logs'|'cache'|'plugins'):Promise<{ok:boolean}>;
  saveConfig(patch:Partial<Omit<ConfigResponse,'hostId'|'apiKeyConfigured'>>):Promise<ConfigResponse>; checkUpdate():Promise<UpdatePlan|null>; downloadUpdate(plan:UpdatePlan):Promise<string>; restartApp():Promise<void>; log(msg:string):Promise<void>;
}
declare global { interface Window { personalhub?:PersonalHubApi } }

const app=document.getElementById('app')!;
type Tab='overview'|'plugins'|'tasks'|'logs'|'lab'|'settings';
let activeTab:Tab='overview';
let metricsTimer:number|undefined;
let metricRange:'minute'|'hour'='minute';
const metricHistory:{cpu:number[];memory:number[];gpu:number[];net:number[]}={cpu:[],memory:[],gpu:[],net:[]};
interface Material { preset:string; alpha:number; blur:number; radius:number; panel:string; ambient:string; accent:string; wallTop:string; wallMid:string; wallBottom:string }
const MATERIAL_STORAGE_KEY='personalhub.appearance.v1';
const MATERIAL_PRESETS:Record<string,{name:string;description:string;material:Material}>={
  clear:{name:'Clear Lens',description:'近乎无雾的通透工具玻璃',material:{preset:'clear',alpha:22,blur:4,radius:14,panel:'18,23,31',ambient:'116,176,255',accent:'#78b5ff',wallTop:'#263348',wallMid:'#101722',wallBottom:'#05070b'}},
  native:{name:'Native Tool',description:'克制、均衡的 macOS 工具质感',material:{preset:'native',alpha:48,blur:24,radius:20,panel:'16,19,25',ambient:'108,168,255',accent:'#6ca8ff',wallTop:'#171c25',wallMid:'#0b0e14',wallBottom:'#040609'}},
  deep:{name:'Deep Space',description:'高对比、低干扰的纯黑工作台',material:{preset:'deep',alpha:78,blur:38,radius:24,panel:'3,5,9',ambient:'103,111,255',accent:'#949bff',wallTop:'#070810',wallMid:'#030408',wallBottom:'#010203'}},
  frost:{name:'Polar Frost',description:'明亮冰霜与冷白高光',material:{preset:'frost',alpha:18,blur:46,radius:28,panel:'205,222,239',ambient:'195,229,255',accent:'#b9e5ff',wallTop:'#486078',wallMid:'#1d2b3a',wallBottom:'#091019'}},
  cobalt:{name:'Cobalt Signal',description:'饱和钴蓝与精密仪器感',material:{preset:'cobalt',alpha:62,blur:28,radius:18,panel:'5,18,44',ambient:'31,104,255',accent:'#3289ff',wallTop:'#071a3c',wallMid:'#030d20',wallBottom:'#01050d'}},
  ember:{name:'Ember Console',description:'暖琥珀、焦黑与夜间控制台',material:{preset:'ember',alpha:66,blur:16,radius:12,panel:'38,15,9',ambient:'255,105,48',accent:'#ff8848',wallTop:'#32140d',wallMid:'#160907',wallBottom:'#070302'}},
};
function loadMaterial():Material{try{const value=JSON.parse(localStorage.getItem(MATERIAL_STORAGE_KEY)??'null') as Partial<Material>|null;if(value&&typeof value.alpha==='number'&&typeof value.blur==='number'&&typeof value.radius==='number')return{...MATERIAL_PRESETS.native.material,...value}}catch{}return{...MATERIAL_PRESETS.native.material}}
let material=loadMaterial();

function esc(value:unknown):string{return String(value??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c))}
function cleanTerminalText(value:string):string{return value.replace(/\u001b\[[0-?]*[ -/]*[@-~]/g,'')}
function fmtTime(iso:string|null):string{if(!iso)return '尚未同步';const d=new Date(iso);return new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d)}
function fmtBytes(value:number|null):string{if(value===null)return '未知大小';if(value<1024)return `${value} B`;if(value<1024*1024)return `${(value/1024).toFixed(1)} KB`;return `${(value/1024/1024).toFixed(1)} MB`}
function elapsed(iso:string):string{const ms=Math.max(0,Date.now()-new Date(iso).getTime());const minutes=Math.floor(ms/60000);if(minutes<1)return '刚刚启动';if(minutes<60)return `${minutes} 分钟`;return `${Math.floor(minutes/60)} 小时 ${minutes%60} 分钟`}
function debug(message:string):void{window.personalhub?.log(message).catch(()=>undefined)}
function exampleInput(schema:CapabilitySummary['inputSchema']):Record<string,unknown>{const result:Record<string,unknown>={};for(const key of schema?.required??[]){const type=schema?.properties?.[key]?.type;result[key]=type==='number'?0:type==='boolean'?false:type==='array'?[]:type==='object'?{}:''}return result}
function curlExample(capability:PluginSummary['capabilities'][number],status:StatusResponse):string{const input=JSON.stringify(exampleInput(capability.inputSchema));return `TASK=$(curl -s -X POST http://${status.apiHost}:${status.apiPort}/v1/tasks -H "Content-Type: application/json" -d '${JSON.stringify({capability:capability.name,input:JSON.parse(input)})}')\nTASK_ID=$(printf '%s' "$TASK" | node -pe "JSON.parse(require('fs').readFileSync(0,'utf8')).taskId")\ncurl -X POST http://${status.apiHost}:${status.apiPort}/v1/tasks/$TASK_ID/execute`}
function parameterRows(schema:CapabilitySummary['inputSchema']):string{const required=new Set(schema?.required??[]);const properties=schema?.properties??{};return Object.entries(properties).map(([name,property])=>`<div class="parameter-row"><code>${esc(name)}</code><span>${esc(property.type)}</span><span class="${required.has(name)?'required':'optional'}">${required.has(name)?'必填':'可选'}</span></div>`).join('')||'<div class="parameter-row empty-params">无输入参数</div>'}
function metricPath(values:number[],max:number):string{if(values.length<2)return '';return values.map((value,index)=>`${index?'L':'M'} ${(index/(values.length-1))*100} ${36-Math.min(Math.max(value/max,0),1)*32}`).join(' ')}
function pushMetric(snapshot:MetricSnapshot):void{const net=(snapshot.netRxBytesPerSec??0)+(snapshot.netTxBytesPerSec??0);for(const [key,value] of Object.entries({cpu:snapshot.cpuPercent??0,memory:snapshot.memoryPercent,gpu:snapshot.gpuUtilPercent??0,net})){const history=metricHistory[key as keyof typeof metricHistory];history.push(value);if(history.length>36)history.shift()}const netMax=Math.max(1024,...metricHistory.net);const entries:[keyof typeof metricHistory,number,string][]=[['cpu',100,snapshot.cpuPercent===undefined?'--':`${snapshot.cpuPercent}%`],['memory',100,`${snapshot.memoryPercent}%`],['gpu',100,snapshot.gpuUtilPercent===undefined?'N/A':`${snapshot.gpuUtilPercent}%`],['net',netMax,`${fmtBytes(net)}/s`]];for(const [key,max,label] of entries){const path=document.querySelector<SVGPathElement>(`[data-metric-path="${key}"]`);if(path)path.setAttribute('d',metricPath(metricHistory[key],max));const value=document.querySelector<HTMLElement>(`[data-metric-value="${key}"]`);if(value)value.textContent=label}const gpuMeta=document.getElementById('gpuMeta');if(gpuMeta)gpuMeta.textContent=snapshot.gpuName?`${snapshot.gpuName}${snapshot.gpuTempC!==undefined?` · ${snapshot.gpuTempC}°C`:''}`:'未检测到独立 GPU'}
function resetMetricHistory():void{for(const history of Object.values(metricHistory))history.length=0}
async function loadMetricHistory(range:'minute'|'hour'):Promise<void>{const samples=await window.personalhub!.getMetricHistory(range);resetMetricHistory();for(const sample of samples)pushMetric(sample);if(!samples.length)pushMetric(await window.personalhub!.getMetrics())}
function startMetrics(initial:MetricSnapshot):void{if(metricsTimer)window.clearInterval(metricsTimer);if(activeTab!=='overview')return;if(metricRange==='minute'){resetMetricHistory();pushMetric(initial);metricsTimer=window.setInterval(()=>{void window.personalhub?.getMetrics().then(pushMetric).catch(()=>undefined)},2000)}else{void loadMetricHistory('hour');metricsTimer=window.setInterval(()=>{void loadMetricHistory('hour')},30000)}}
function badge(status:string):string{const tone=status==='succeeded'||status==='running'?'ok':status==='failed'?'fail':'warn';return `<span class="badge ${tone}">${esc(status)}</span>`}
function card(content:string,extra=''):string{return `<article class="card glass ${extra}"><div class="card-body">${content}</div></article>`}
function pageHead(kicker:string,title:string,subtitle:string,meta=''):string{return `<div class="page-head"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${meta}</div>`}
function nav():string{return ([['overview','概览'],['plugins','插件'],['tasks','任务'],['logs','日志'],['lab','外观'],['settings','设置']] as Array<[Tab,string]>).map(([tab,label])=>`<button class="nav-button ${activeTab===tab?'active':''}" data-tab="${tab}">${label}</button>`).join('')}
function applyMaterial(next:Material,persist=true):void{material={...next};const root=document.documentElement;root.style.setProperty('--glass-alpha',String(material.alpha/100));root.style.setProperty('--glass-blur',`${material.blur}px`);root.style.setProperty('--radius',`${material.radius}px`);root.style.setProperty('--panel-rgb',material.panel);root.style.setProperty('--ambient-rgb',material.ambient);root.style.setProperty('--accent',material.accent);root.style.setProperty('--wall-top',material.wallTop);root.style.setProperty('--wall-mid',material.wallMid);root.style.setProperty('--wall-bottom',material.wallBottom);if(persist)localStorage.setItem(MATERIAL_STORAGE_KEY,JSON.stringify(material));const alphaOut=document.getElementById('alphaValue');const blurOut=document.getElementById('blurValue');const radiusOut=document.getElementById('radiusValue');if(alphaOut)alphaOut.textContent=`${material.alpha}%`;if(blurOut)blurOut.textContent=`${material.blur}px`;if(radiusOut)radiusOut.textContent=`${material.radius}px`}
applyMaterial(material,false);

async function render():Promise<void>{
  if(!window.personalhub){app.innerHTML='<div class="empty"><div><strong>主进程未连接</strong><span>Preload bridge 不可用</span></div></div>';return}
  try{
    const status=await window.personalhub.getStatus();if(!status)throw new Error('PersonalHub 尚未初始化');
    const content=await renderTab(status);
    const running=status.agentStatus==='running';const remoteOnline=status.remoteStatus==='online';
    const remoteLabel:Record<RemoteStatus,string>={unconfigured:'未配置远程连接',connecting:'正在连接',online:'远程在线',degraded:'连接异常',offline:'远程离线'};
    app.innerHTML=`<div class="app-shell ${status.platform==='darwin'?'mac-immersive':''}"><div class="app-frame">
      <header class="topbar glass"><div class="brand"><div class="brand-mark">P</div><div><strong>PersonalHub</strong><small>Local AI Worker</small></div></div><nav class="nav">${nav()}</nav><div class="top-actions"><span class="connection ${remoteOnline?'online':'offline'}">${remoteLabel[status.remoteStatus]}</span><button class="tool-btn" id="topRefresh">刷新</button></div></header>
      <main class="workspace"><div class="workspace-inner view-enter">${content}</div></main>
    </div></div>`;
    bindEvents();
    startMetrics(status);
  }catch(error){const message=error instanceof Error?error.message:String(error);debug(`render failed: ${message}`);app.innerHTML=`<div class="empty error"><div><strong>界面加载失败</strong><span>${esc(message)}</span></div></div>`}
}

async function renderTab(status:StatusResponse):Promise<string>{
  const hostMeta=`<code class="host-id">${esc(status.hostId??'未分配 Host ID')}</code>`;
  if(activeTab==='plugins'){
    const plugins=await window.personalhub!.getPlugins();
    const body=plugins.length?`<div class="plugin-stack">${plugins.map((plugin)=>{const capabilities=plugin.capabilities.map((cap)=>{const command=curlExample(cap,status);const createUrl=`http://${status.apiHost}:${status.apiPort}/v1/tasks`;const executeUrl=`http://${status.apiHost}:${status.apiPort}/v1/tasks/{taskId}/execute`;return `<section class="capability-row"><div class="capability-title"><span><strong>${esc(cap.name)}</strong><small>${esc(cap.description??'本地任务能力')}</small></span><span class="method">POST</span></div><div class="endpoint-list"><div><span>创建任务</span><code>${esc(createUrl)}</code><button class="tool-btn" data-copy="${esc(createUrl)}">复制 URL</button></div><div><span>执行任务</span><code>${esc(executeUrl)}</code><button class="tool-btn" data-copy="${esc(executeUrl)}">复制 URL</button></div></div><div class="parameter-table"><div class="detail-label">输入参数</div>${parameterRows(cap.inputSchema)}</div><div class="capability-detail"><div><span>返回 Schema</span><pre>${esc(JSON.stringify(cap.outputSchema??{},null,2))}</pre></div><div><span>请求体与 curl</span><pre>${esc(command)}</pre><button class="tool-btn copy-call" data-copy="${esc(command)}">复制完整调用</button></div></div></section>`}).join('');const deployment=plugin.deployment?`${plugin.deployment.type} · 已声明`:'未声明部署方式';return card(`<div class="plugin-head"><div class="icon-box">${esc(plugin.name.slice(0,1).toUpperCase())}</div><div><h3>${esc(plugin.name)}</h3><p>${esc(plugin.reason??plugin.description??'暂无描述')}</p></div><span class="badge ${plugin.status==='registered'?'ok':plugin.status==='error'?'fail':'warn'}">${esc(plugin.status)}</span></div><div class="plugin-meta"><span><b>${esc(plugin.id)}</b> ID</span><span><b>${esc(plugin.version)}</b> VERSION</span><span><b>${esc(plugin.runtime)}</b> RUNTIME</span><span><b>v${plugin.schemaVersion}</b> MANIFEST</span><span><b>${esc(deployment)}</b> DEPLOYMENT</span></div><div class="capability-list">${capabilities}</div><div class="toolbar plugin-actions"><button class="tool-btn" data-copy="${esc(JSON.stringify({schemaVersion:plugin.schemaVersion,id:plugin.id,runtime:plugin.runtime},null,2))}">复制信息</button><button class="tool-btn" data-plugin-toggle="${esc(plugin.id)}" data-plugin-enabled="${plugin.enabled}">${plugin.enabled?'禁用':'启用'}</button><button class="tool-btn danger" data-plugin-delete="${esc(plugin.id)}">删除</button></div>`,'plugin-card-wide')}).join('')}</div>`:`<div class="empty"><div><strong>尚未安装插件</strong><span>导入包含 manifest.json 的插件目录</span></div></div>`;
    return pageHead('Capabilities','插件','声明、调用方式与部署准备','<button class="tool-btn primary" id="importPlugin">导入插件</button>')+body;
  }
  if(activeTab==='tasks'){
    const [tasks,capabilities]=await Promise.all([window.personalhub!.getTasks(),window.personalhub!.getCapabilities()]);
    const options=capabilities.map((cap)=>`<option value="${esc(cap.name)}" data-example="${esc(JSON.stringify(exampleInput(cap.inputSchema)))}" data-required="${esc(JSON.stringify(cap.inputSchema?.required??[]))}">${esc(cap.name)} · ${esc(cap.pluginId)}</option>`).join('');
    const initialInput=JSON.stringify(exampleInput(capabilities[0]?.inputSchema),null,2);
    const composer=card(`<div class="section-title"><h3>发起任务</h3><span>本机立即执行</span></div>${capabilities.length?`<form id="taskForm" class="task-compose"><select id="taskCapability" name="capability" aria-label="能力">${options}</select><textarea id="taskInput" name="input" spellcheck="false" aria-label="输入 JSON">${esc(initialInput)}</textarea><button class="tool-btn primary" type="submit">发起并执行</button></form>`:`<div class="notice">当前没有已注册且启用的能力，无法发起任务。</div>`}`,'task-composer');
    const rows=tasks.map((task)=>{const artifacts=task.artifacts??[];const artifactRows=artifacts.map((artifact)=>`<div class="artifact-row"><span class="artifact-state ${artifact.exists?'available':'missing'}"></span><div><strong>${esc(artifact.name)}</strong><code title="${esc(artifact.localPath)}">${esc(artifact.localPath)}</code></div><span>${esc(fmtBytes(artifact.sizeBytes))}</span><button class="tool-btn" data-artifact-task="${esc(task.taskId)}" data-artifact-path="${esc(artifact.localPath)}" ${artifact.exists?'':'disabled'}>定位</button></div>`).join('');return `<details class="task-row" data-task-row data-status="${esc(task.status)}" data-search="${esc(`${task.capability} ${task.pluginId} ${task.taskId}`.toLowerCase())}"><summary><span class="task-chevron">›</span><span><strong>${esc(task.capability)}</strong><small>${esc(task.pluginId)}</small></span><code>${esc(task.taskId.slice(0,8))}</code>${badge(task.status)}<span>${artifacts.length?`${artifacts.length} 个产物`:'无产物'}</span><time>${esc(fmtTime(task.updatedAt))}</time></summary><div class="task-detail"><div class="task-json"><div><span>输入</span><pre>${esc(JSON.stringify(task.input,null,2))}</pre></div><div><span>${task.error?'错误':'输出'}</span><pre class="${task.error?'error':''}">${esc(task.error?cleanTerminalText(task.error.message):JSON.stringify(task.output,null,2)??'暂无输出')}</pre></div></div>${artifacts.length?`<div class="artifact-list"><div class="detail-label">产物位置</div>${artifactRows}</div>`:''}<div class="task-actions"><label><input type="checkbox" data-delete-artifacts="${esc(task.taskId)}" ${artifacts.some((item)=>item.exists)?'':'disabled'}> 同时删除本地产物</label><button class="tool-btn danger" data-task-delete="${esc(task.taskId)}">删除记录</button></div></div></details>`}).join('');
    const history=card(`<div class="task-toolbar"><div><strong>任务记录</strong><span id="taskVisibleCount">${tasks.length} / ${tasks.length}</span></div><input id="taskSearch" type="search" placeholder="搜索能力、插件或 ID"><select id="taskStatusFilter" aria-label="状态筛选"><option value="all">全部状态</option><option value="running">运行中</option><option value="queued">排队中</option><option value="succeeded">成功</option><option value="failed">失败</option></select></div>${tasks.length?`<div class="task-table-head"><span></span><span>能力 / 插件</span><span>ID</span><span>状态</span><span>产物</span><span>更新时间</span></div><div class="task-rows">${rows}</div>`:`<div class="empty compact"><div><strong>还没有任务记录</strong><span>可在上方发起本地任务，或等待 AdminOS 下发任务</span></div></div>`}`,'task-history');
    return pageHead('Execution','任务','创建、执行、产物与历史记录',`<span class="chip">${tasks.length} 条记录</span>`)+`<div class="grid task-page">${composer}${history}</div>`;
  }
  if(activeTab==='logs'){
    const logs=await window.personalhub!.getLogs();
    return pageHead('Diagnostics','日志','主进程、连接器与渲染器诊断信息','<button class="tool-btn" id="refreshLogs">刷新日志</button>')+card(`<div class="log-shell"><div class="section-title"><h3>personalhub-debug.log</h3><span>最近 100 KB</span></div><pre class="logs">${esc(logs||'暂无日志')}</pre></div>`);
  }
  if(activeTab==='settings'){
    const [config,storage]=await Promise.all([window.personalhub!.getConfig(),window.personalhub!.getStorageInfo()]);if(!config)return pageHead('Preferences','设置','配置尚不可用');
    return pageHead('Preferences','设置','连接、身份、存储与数据保留',hostMeta)+`<div class="grid settings-page">${card(`<form id="settingsForm" class="settings">
      <label>主机名称<input name="name" value="${esc(config.name)}" required></label><label>同步间隔（毫秒）<input name="agentIntervalMs" type="number" min="1000" value="${config.agentIntervalMs}" required></label>
      <label class="wide">AdminOS 地址<input name="serverUrl" value="${esc(config.serverUrl??'')}" placeholder="https://volc.zusheng.cc"></label>
      <label class="wide">调度 API Key<div class="input-row"><input id="apiKeyInput" name="apiKey" type="password" value="" placeholder="${config.apiKeyConfigured?'已配置，留空则保持不变':'输入 API Key'}"><button type="button" class="tool-btn" id="toggleApiKey">显示</button></div></label>
      <label>诊断数据保留天数<input name="logRetentionDays" type="number" min="1" max="90" value="${config.logRetentionDays}" required></label><div></div>
      <label class="checkbox"><input name="startOnLogin" type="checkbox" ${config.startOnLogin?'checked':''}> Windows 登录后自动启动 PersonalHub</label>
      <div class="wide toolbar"><button class="tool-btn primary" type="submit">保存设置</button><button class="tool-btn" type="button" id="restartApp">重启应用</button></div>
    </form>`)}${card(`<div class="section-title"><h3>存储与诊断</h3><span>大小最多缓存 60 秒</span></div><div class="storage-list"><div><span>日志与性能数据</span><strong>${esc(fmtBytes(storage.logsBytes))}</strong><code title="${esc(storage.logsPath)}">${esc(storage.logsPath)}</code><button class="tool-btn" data-open-storage="logs">打开</button></div><div><span>应用缓存</span><strong>${esc(fmtBytes(storage.cacheBytes))}</strong><code title="${esc(storage.cachePath)}">${esc(storage.cachePath)}</code><button class="tool-btn" data-open-storage="cache">打开</button></div><div><span>插件目录</span><strong>${esc(fmtBytes(storage.pluginsBytes))}</strong><code title="${esc(storage.pluginsPath)}">${esc(storage.pluginsPath)}</code><button class="tool-btn" data-open-storage="plugins">打开</button></div></div><div class="notice" style="margin-top:12px">性能数据每 30 秒写入一次按天 JSONL；界面的 2 秒分钟图仅保存在内存中。</div>`,'storage-card')}</div>`;
  }
  if(activeTab==='lab'){
    const presets=Object.entries(MATERIAL_PRESETS).map(([id,preset])=>`<button class="preset ${material.preset===id?'active':''}" data-preset="${id}"><strong>${esc(preset.name)}</strong><small>${esc(preset.description)}</small></button>`).join('');
    return pageHead('Appearance Lab','视觉实验室','高反差材质预设与实时参数会自动保存','<span class="chip">已持久化</span>')+`<div class="lab-grid">
      ${card(`<div class="section-title"><h3>材质预设</h3><span>${Object.keys(MATERIAL_PRESETS).length} Presets</span></div><div class="preset-list">${presets}</div>`)}
      <div class="grid"><div class="preview-stage"><div class="preview-card glass"><div class="eyebrow">MATERIAL PREVIEW</div><h3>PersonalHub Lens</h3><p>透明度、模糊与圆角会立即作用到整个应用。</p><div class="chips" style="margin-top:14px"><span class="chip">Local First</span><span class="chip">Apple Native</span></div></div></div>
      ${card(`<div class="section-title"><h3>材质参数</h3><span>实时</span></div><div class="control-list"><label class="control"><div class="control-head"><span>面板透明度</span><output id="alphaValue">${material.alpha}%</output></div><input id="alphaControl" type="range" min="18" max="82" value="${material.alpha}"></label><label class="control"><div class="control-head"><span>背景模糊</span><output id="blurValue">${material.blur}px</output></div><input id="blurControl" type="range" min="0" max="48" value="${material.blur}"></label><label class="control"><div class="control-head"><span>卡片圆角</span><output id="radiusValue">${material.radius}px</output></div><input id="radiusControl" type="range" min="10" max="30" value="${material.radius}"></label></div>`)}</div>
    </div>`;
  }
  const running=status.agentStatus==='running';const tick=status.lastTick;
  return pageHead('Overview','运行概览','本机 AI 服务、远程调度与执行状态',hostMeta)+`
    ${card(`<div class="hero"><div class="orb">⌘</div><div><h2>${running?'准备接收远程任务':'远程调度已暂停'}</h2><p>${running?'PersonalHub 正在主动同步能力并领取任务。':'本机插件与 Ollama 不受影响，adminOS 暂时无法调度。'}</p><div class="chips"><span class="chip">${esc(status.connector)}</span><span class="chip">本地 API ${esc(status.apiPort)}</span></div></div></div><div class="stat-band"><div class="stat"><span>插件</span><strong>${status.pluginCount}</strong><small>${status.capabilityCount} 个能力</small></div><div class="stat"><span>能力</span><strong>${status.capabilityCount}</strong><small>可调度</small></div><div class="stat"><span>任务</span><strong>${status.taskCount}</strong><small>${tick?`${tick.succeeded} 成功`:'等待循环'}</small></div><div class="stat"><span>内存</span><strong>${status.memoryPercent}%</strong><small>仅指标</small></div></div>`,'overview-card')}
    <div class="metric-bar"><div><strong>性能趋势</strong><span>${metricRange==='minute'?'2 秒实时采样':'30 秒持久化采样'}</span></div><div class="segmented"><button class="${metricRange==='minute'?'active':''}" data-metric-range="minute">分钟</button><button class="${metricRange==='hour'?'active':''}" data-metric-range="hour">小时</button></div></div>
    <div class="metric-grid">
      ${[['cpu','CPU','处理器负载'],['memory','RAM','内存占用'],['gpu','GPU','图形处理器'],['net','NET','上下行合计']].map(([key,label,meta])=>card(`<div class="metric-head"><span>${label}</span><strong data-metric-value="${key}">--</strong></div><svg class="metric-chart" viewBox="0 0 100 40" preserveAspectRatio="none" aria-label="${label} 趋势"><path class="metric-grid-line" d="M 0 36 L 100 36 M 0 20 L 100 20 M 0 4 L 100 4"></path><path class="metric-line metric-${key}" data-metric-path="${key}" d=""></path></svg><small ${key==='gpu'?'id="gpuMeta"':''}>${meta}</small>`,'metric-card')).join('')}
    </div>
    <div class="grid overview-grid">
      ${card(`<div class="section-title"><h3>远程调度状态</h3><span>${esc(status.remoteStatus)}</span></div><div class="summary"><div><span>最近成功心跳</span><strong>${esc(fmtTime(status.lastHeartbeatSuccessAt))}</strong></div><div><span>连续失败</span><strong>${status.consecutiveHeartbeatFailures}</strong></div><div><span>运行时长</span><strong>${esc(elapsed(status.startedAt))}</strong></div></div>${status.configurationIssue?`<p class="error">${esc(status.configurationIssue)}</p>`:''}${status.lastRemoteError?`<p class="error">${esc(status.lastRemoteError)}</p>`:''}<div class="toolbar" style="margin-top:16px"><button class="tool-btn ${running?'danger':'primary'}" id="toggleScheduling">${running?'停止远程调度':'启动远程调度'}</button><button class="tool-btn" id="runTick" ${running?'':'disabled'}>立即同步</button><button class="tool-btn" id="checkUpdate">检查更新</button></div><pre class="result" id="actionOutput"></pre>`)}
    </div>`;
}

function toast(message:string):void{document.querySelector('.toast')?.remove();const node=document.createElement('div');node.className='toast';node.textContent=message;document.body.appendChild(node);window.setTimeout(()=>node.remove(),3200)}
async function runAction(button:HTMLButtonElement|undefined,action:()=>Promise<void>):Promise<void>{if(button)button.disabled=true;try{await action()}catch(error){toast(error instanceof Error?error.message:String(error))}finally{if(button)button.disabled=false}}
function bindEvents():void{
  document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach((button)=>button.addEventListener('click',()=>{activeTab=button.dataset.tab as Tab;void render()}));
  document.querySelectorAll<HTMLButtonElement>('[data-plugin-toggle]').forEach((button)=>button.addEventListener('click',()=>void runAction(button,async()=>{const id=button.dataset.pluginToggle!;const enabled=button.dataset.pluginEnabled==='true';await window.personalhub!.setPluginEnabled(id,!enabled);toast(`${enabled?'已禁用':'已启用'} ${id}，重启后生效`);await render()})));
  document.querySelectorAll<HTMLButtonElement>('[data-plugin-delete]').forEach((button)=>button.addEventListener('click',()=>{const id=button.dataset.pluginDelete!;if(!window.confirm(`确认删除插件 ${id}？此操作会删除插件目录。`))return;void runAction(button,async()=>{await window.personalhub!.deletePlugin(id);toast(`已删除 ${id}，重启后同步服务列表`);await render()})}));
  const importButton=document.getElementById('importPlugin') as HTMLButtonElement|undefined;importButton?.addEventListener('click',()=>void runAction(importButton,async()=>{const imported=await window.personalhub!.importPlugin();if(!imported)return;toast(`已导入 ${imported.name}`);await render()}));
  document.querySelectorAll<HTMLButtonElement>('[data-copy]').forEach((button)=>button.addEventListener('click',(event)=>{event.preventDefault();event.stopPropagation();void runAction(button,async()=>{await window.personalhub!.copyText(button.dataset.copy??'');toast('已复制到剪贴板')})}));
  document.querySelectorAll<HTMLButtonElement>('[data-metric-range]').forEach((button)=>button.addEventListener('click',()=>{metricRange=button.dataset.metricRange as 'minute'|'hour';void render()}));
  document.querySelectorAll<HTMLButtonElement>('[data-open-storage]').forEach((button)=>button.addEventListener('click',()=>void runAction(button,async()=>{await window.personalhub!.openStoragePath(button.dataset.openStorage as 'logs'|'cache'|'plugins')})));
  document.getElementById('topRefresh')?.addEventListener('click',()=>void render());document.getElementById('refreshLogs')?.addEventListener('click',()=>void render());
  const toggle=document.getElementById('toggleScheduling') as HTMLButtonElement|undefined;toggle?.addEventListener('click',()=>void runAction(toggle,async()=>{const status=await window.personalhub!.getStatus();if(status?.agentStatus==='running')await window.personalhub!.stopAgent();else await window.personalhub!.startAgent();await render()}));
  const runTick=document.getElementById('runTick') as HTMLButtonElement|undefined;runTick?.addEventListener('click',()=>void runAction(runTick,async()=>{const result=await window.personalhub!.runAgentTick();toast(`同步完成 · ${result.tasksProcessed} 个任务`);await render()}));
  document.getElementById('taskForm')?.addEventListener('submit',(event)=>{event.preventDefault();const form=event.currentTarget as HTMLFormElement;void runAction(form.querySelector('button[type="submit"]') as HTMLButtonElement,async()=>{const values=new FormData(form);const capability=String(values.get('capability')??'');let input:unknown;try{input=JSON.parse(String(values.get('input')??'{}'))}catch{throw new Error('输入必须是有效的 JSON')}const required=JSON.parse((document.getElementById('taskCapability') as HTMLSelectElement).selectedOptions[0]?.dataset.required??'[]') as string[];const record=input&&typeof input==='object'?input as Record<string,unknown>:{};const empty=required.find((key)=>typeof record[key]==='string'&&!String(record[key]).trim());if(empty)throw new Error(`必填字段 ${empty} 不能为空`);const task=await window.personalhub!.createTask(capability,input,true);toast(task.status==='succeeded'?'任务执行成功':`任务状态：${task.status}`);await render()})});
  document.getElementById('taskCapability')?.addEventListener('change',(event)=>{const select=event.currentTarget as HTMLSelectElement;const input=document.getElementById('taskInput') as HTMLTextAreaElement|null;const example=select.selectedOptions[0]?.dataset.example;if(input&&example)input.value=JSON.stringify(JSON.parse(example),null,2)});
  const applyTaskFilters=()=>{const query=(document.getElementById('taskSearch') as HTMLInputElement|null)?.value.trim().toLowerCase()??'';const status=(document.getElementById('taskStatusFilter') as HTMLSelectElement|null)?.value??'all';let visible=0;document.querySelectorAll<HTMLElement>('[data-task-row]').forEach((row)=>{const show=(!query||row.dataset.search?.includes(query))&&(status==='all'||row.dataset.status===status);row.hidden=!show;if(show)visible+=1});const count=document.getElementById('taskVisibleCount');if(count)count.textContent=`${visible} / ${document.querySelectorAll('[data-task-row]').length}`};document.getElementById('taskSearch')?.addEventListener('input',applyTaskFilters);document.getElementById('taskStatusFilter')?.addEventListener('change',applyTaskFilters);
  document.querySelectorAll<HTMLButtonElement>('[data-artifact-task]').forEach((button)=>button.addEventListener('click',()=>void runAction(button,async()=>{await window.personalhub!.revealArtifact(button.dataset.artifactTask!,button.dataset.artifactPath!)})));
  document.querySelectorAll<HTMLButtonElement>('[data-task-delete]').forEach((button)=>button.addEventListener('click',()=>{const taskId=button.dataset.taskDelete!;if(!window.confirm(`确认删除任务记录 ${taskId.slice(0,8)}？`))return;void runAction(button,async()=>{const checkbox=document.querySelector<HTMLInputElement>(`[data-delete-artifacts="${taskId}"]`);const result=await window.personalhub!.deleteTask(taskId,Boolean(checkbox?.checked));toast(result.deletedArtifacts?`记录与 ${result.deletedArtifacts} 个产物已删除`:'任务记录已删除');await render()})}));
  const update=document.getElementById('checkUpdate') as HTMLButtonElement|undefined;update?.addEventListener('click',()=>void runAction(update,async()=>{const plan=await window.personalhub!.checkUpdate();if(!plan){toast('当前已是最新版本');return}toast(`正在下载 ${plan.artifactName}`);const path=await window.personalhub!.downloadUpdate(plan);toast(`更新包已校验：${path}`)}));
  document.getElementById('toggleApiKey')?.addEventListener('click',()=>{const input=document.getElementById('apiKeyInput') as HTMLInputElement|null;if(!input)return;input.type=input.type==='password'?'text':'password'});
  document.getElementById('restartApp')?.addEventListener('click',()=>void window.personalhub!.restartApp());
  const bindRange=(id:string,callback:(value:number)=>void)=>document.getElementById(id)?.addEventListener('input',(event)=>callback(Number((event.currentTarget as HTMLInputElement).value)));
  bindRange('alphaControl',(value)=>applyMaterial({...material,preset:'custom',alpha:value}));
  bindRange('blurControl',(value)=>applyMaterial({...material,preset:'custom',blur:value}));
  bindRange('radiusControl',(value)=>applyMaterial({...material,preset:'custom',radius:value}));
  document.querySelectorAll<HTMLButtonElement>('[data-preset]').forEach((button)=>button.addEventListener('click',()=>{const id=button.dataset.preset??'native';const preset=MATERIAL_PRESETS[id];if(!preset)return;applyMaterial({...preset.material});const alphaInput=document.getElementById('alphaControl') as HTMLInputElement|null;const blurInput=document.getElementById('blurControl') as HTMLInputElement|null;const radiusInput=document.getElementById('radiusControl') as HTMLInputElement|null;if(alphaInput)alphaInput.value=String(material.alpha);if(blurInput)blurInput.value=String(material.blur);if(radiusInput)radiusInput.value=String(material.radius);document.querySelectorAll('.preset').forEach((item)=>item.classList.remove('active'));button.classList.add('active');toast(`${preset.name} 已应用并保存`)}));
  document.getElementById('settingsForm')?.addEventListener('submit',(event)=>{event.preventDefault();const form=event.currentTarget as HTMLFormElement;void runAction(form.querySelector('button[type="submit"]') as HTMLButtonElement,async()=>{const values=new FormData(form);const apiKey=String(values.get('apiKey')??'').trim();await window.personalhub!.saveConfig({name:String(values.get('name')??''),serverUrl:String(values.get('serverUrl')??'')||null,...(apiKey?{apiKey}:{}),agentIntervalMs:Number(values.get('agentIntervalMs')),logRetentionDays:Number(values.get('logRetentionDays')),startOnLogin:values.get('startOnLogin')==='on'});toast('设置已保存；连接信息变更需重启生效')})});
}

void render();
